# Universidade de Vassouras - Maricá
# Estrutura de Dados
# Márcio Garrido
# 202211182
# Hugo Lelly de Lima Marinho

# 02) Carregue a data atual do computador e apresente somente a data.

print(f'\n\t Universidade de Vassouras - Maricá \n\t Estrutura de Dados - Márcio Garrido \n\t 202211182 - Hugo Lelly de Lima Marinho')
print(f'\n\t 02) Carregue a data atual do computador e apresente somente a data.')

import datetime

data = datetime.date.today()

print(f'\n\t A data atual é {data}.')