# Universidade de Vassouras - Maricá
# Estrutura de Dados
# Márcio Garrido
# 202211182
# Hugo Lelly de Lima Marinho

# 04) Desenvolva um programa que leia um número inteiro qualquer e que apresente o número informado com duas casas decimais.

print(f'\n\t Universidade de Vassouras - Maricá \n\t Estrutura de Dados - Márcio Garrido \n\t 202211182 - Hugo Lelly de Lima Marinho')
print(f'\n\t 04) Desenvolva um programa que leia um número inteiro qualquer e que apresente o número informado com duas casas decimais.')

numero = int(input(f'\n\t Digite um número inteiro: '))

print(f'\n\t O número {numero} com duas casas decimais é: {numero:.2f}')